M48
; DRILL file {KiCad (6.0.1-0)} date Dienstag, 18. Januar 2022 um 10:49:35
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-18T10:49:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.4526Y-3.805
X3.4526Y-4.9074
X4.5549Y-3.805
X4.5549Y-4.9074
T0
M30
